version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-bri
    command: bash -c "redis-server --requirepass sudosu"
    ports:
      - 6379:6379
    volumes:
      - type: bind
        source: /Users/sarimin/code/docker/redis/data
        target: /data 